/*
 * drs4_defines.h
 *
 *  Created on: Sep 17, 2018
 *      Author: taxidev
 */

#ifndef SOURCE_DIRECTORY__SRC_LIBTAXIHAL_HAL_DRS4_DEFINES_H_
#define SOURCE_DIRECTORY__SRC_LIBTAXIHAL_HAL_DRS4_DEFINES_H_

#define BASE_DRS4										0x0

#define OFFS_DRS4_NUMBEROFSAMPLESTOREAD					0x10a6
#define OFFS_DRS4_READOUTMODE							0x10aa

#define OFFS_DRS4_CORRECTIONRAMCHANNELMASK				0x10e0
#define OFFS_DRS4_CORRECTIONRAMADDRESS					0x10e2
#define OFFS_DRS4_CORRECTIONRAMWRITEVALUE				0x10e4

#endif /* SOURCE_DIRECTORY__SRC_LIBTAXIHAL_HAL_DRS4_DEFINES_H_ */
