#! /bin/sh
#
# hess1u-sync syncs the /opt/hess1u folder
#
# Author:	Gianluca Giavitto,   <gianluca.giavitto@desy.de>
#

echo_success() {
  echo -n "OK"
  return 0
}

echo_failure() {
  echo -n "FAILED"
  return 1
}

RETVAL=0

# See how we were called.
case "$1" in
    start)
        echo -n "Syncing /opt/hess1u : "
        rsync -a -e "ssh -i /etc/dropbear/dropbear_rsa_host_key" \
        camerapc:/opt/hess1u/nfs/root/opt/hess1u /opt/
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then echo_success; 
        else echo_failure; exit $RETVAL; 
        fi
        echo
        ;;
    stop)
        ;;
    restart)
        ;;
    status)
        ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
esac

exit $RETVAL
