// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/exampleSlowControl.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::taxi;

class exampleSlowControlHandler : virtual public exampleSlowControlIf {
 public:
  exampleSlowControlHandler() {
    // Your initialization goes here
  }

  void startSoftTriggers(const double frequency, const int32_t numTriggers) {
    // Your implementation goes here
    printf("startSoftTriggers\n");
  }

  void doSomething(const int16_t a, const bool b) {
    // Your implementation goes here
    printf("doSomething\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<exampleSlowControlHandler> handler(new exampleSlowControlHandler());
  shared_ptr<TProcessor> processor(new exampleSlowControlProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

